import { useEffect, useState } from 'react';
import { request, apiUrl } from '../api';
import { Kpis, PriorityTable } from './Summary';
import Evidence from './Evidence';
import { Empty } from './ui';
import Icon from './Icon';
import { dateLabel, number } from '../format';
export default function Reports({ selectedId, onSelect, refresh }) {
  const [reports, setReports] = useState([]);
  const [report, setReport] = useState(null);
  const [error, setError] = useState('');
  const [evidence, setEvidence] = useState(null);
  useEffect(() => {
    let active = true;
    request('/reports')
      .then((r) => {
        if (active) setReports(r.reports);
      })
      .catch((e) => {
        if (active) setError(e.message);
      });
    return () => {
      active = false;
    };
  }, [refresh, selectedId]);
  useEffect(() => {
    if (!selectedId) {
      setReport(null);
      return;
    }
    const controller = new AbortController();
    setReport(null);
    setError('');
    request(`/reports/${selectedId}`, { signal: controller.signal })
      .then(setReport)
      .catch((e) => {
        if (e.name !== 'AbortError') setError(e.message);
      });
    return () => controller.abort();
  }, [selectedId]);
  return (
    <>
      {error && (
        <div className="error" role="alert">
          {error}
        </div>
      )}
      {!selectedId ? (
        <section className="panel report-archive">
          <header className="section-head">
            <div>
              <h2>Your saved reports</h2>
              <p>Every report generated by your account, preserved for review and handover.</p>
            </div>
            <span className="quiet-label">{reports.length} saved reports</span>
          </header>
          {reports.length ? (
            <div className="report-list">
              {reports.map((r) => (
                <button className="report-list-row" key={r.id} onClick={() => onSelect(r.id)}>
                  <span className="report-file">
                    <Icon name="document" size={21} />
                  </span>
                  <div>
                    <strong>{r.title}</strong>
                    <small>
                      {dateLabel(r.period_start)} – {dateLabel(r.period_end)},{' '}
                      {r.period_end.slice(0, 4)}
                    </small>
                  </div>
                  <time>Saved {dateLabel(r.created_at)}</time>
                  <Icon name="chevron" size={18} />
                </button>
              ))}
            </div>
          ) : (
            <Empty title="Your reporting history starts here">
              Open Generate report in the sidebar to save your first analysis. Each saved report
              keeps its original figures and evidence.
            </Empty>
          )}
        </section>
      ) : report ? (
        <article className="saved-report">
          <div className="report-toolbar">
            <button className="inline-link" onClick={() => onSelect(null)}>
              ← All reports
            </button>
            <div>
              <a className="button secondary small" href={apiUrl(`/reports/${report.id}/download`)}>
                <Icon name="download" size={15} />
                Download report
              </a>
              <button className="button secondary small" onClick={() => window.print()}>
                Print / Save PDF
              </button>
            </div>
          </div>
          <header className="report-title">
            <span className="section-number">
              PERFORMANCE REPORT · SAVED {dateLabel(report.created_at).toUpperCase()}
            </span>
            <h1>Customer feedback performance</h1>
            <p>
              {dateLabel(report.scope.start)} – {dateLabel(report.scope.end)},{' '}
              {report.scope.end.slice(0, 4)}
            </p>
            <small>
              Frozen snapshot · analysis {report.scope.published_run.id.slice(0, 8)} ·{' '}
              {report.scope.published_run.engine} discovery
            </small>
          </header>
          <Kpis summary={report.summary} />
          <section className="report-section">
            <h2>What the feedback shows</h2>
            {report.narrative.map((p, i) => (
              <p key={i}>{p}</p>
            ))}
          </section>
          <section className="report-section">
            <h2>Where complaints are concentrated</h2>
            <p>Click a category to inspect the evidence saved with this report.</p>
            <PriorityTable categories={report.categories} onEvidence={setEvidence} expanded />
          </section>
          {[
            ['services', 'Supplied service areas'],
            ['segments', 'Supplied customer segments'],
          ].map(
            ([key, title]) =>
              report[key].length > 0 && (
                <section className="report-section" key={key}>
                  <h2>{title}</h2>
                  <table className="breakdown">
                    <thead>
                      <tr>
                        <th>{key === 'services' ? 'Service' : 'Segment'}</th>
                        <th>Feedback records</th>
                        <th>Negative reviews</th>
                        <th>Negative rate</th>
                      </tr>
                    </thead>
                    <tbody>
                      {report[key].map((r) => (
                        <tr key={r.name}>
                          <td>{r.name}</td>
                          <td>{r.total}</td>
                          <td>{r.negative}</td>
                          <td>{r.negative_rate}%</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </section>
              ),
          )}
          <section className="report-section report-methods">
            <h2>Coverage and interpretation</h2>
            <p>
              {number(report.summary.ungrouped_negative)} negative reviews were ungrouped.{' '}
              {number(report.summary.customer_coverage)} records included a customer identifier;{' '}
              {number(report.summary.known_customers)} distinct identifiers were observed. Missing
              metadata is never inferred.
            </p>
            {Object.entries(report.methodology).map(([key, value]) => (
              <p key={key}>
                <strong>{key.charAt(0).toUpperCase() + key.slice(1)}. </strong>
                {value}
              </p>
            ))}
            <small>
              Later data imports, category renames and model runs do not change this report.
            </small>
          </section>
          {evidence && (
            <Evidence
              category={evidence}
              reportId={report.id}
              days={report.scope.days}
              onClose={() => setEvidence(null)}
            />
          )}
        </article>
      ) : (
        <div className="loading">Loading the saved report…</div>
      )}
    </>
  );
}
