const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const base = process.env.SIGNAL_TEST_URL || 'http://127.0.0.1:8001';
(async () => {
 const browser = await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL || 'msedge'});
 const page = await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});
 const errors=[];const passed=[];page.on('pageerror',e=>errors.push(e.message));
 const nav=name=>page.getByRole('navigation').getByRole('button',{name,exact:true});
 const noOverflow=async()=>assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.goto(base);await page.getByRole('heading',{name:'Welcome back'}).waitFor();await page.screenshot({path:'qa/sign-in-v3.png',fullPage:true,animations:'disabled'});
 const username='qa-'+Date.now();const password='Account-browser-test-passphrase';
 await page.getByRole('button',{name:'Create an account',exact:true}).click();await page.getByLabel('Username',{exact:true}).fill(username);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByLabel('Confirm password',{exact:true}).fill(password);await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Create account',exact:true}).click();await page.locator('.kpi').first().waitFor();assert.equal(await page.locator('.trend-chart').count(),0);assert.equal(await page.locator('.priority-table').count(),0);await page.screenshot({path:'qa/dashboard-v3-desktop.png',fullPage:true,animations:'disabled'});assert.equal(await page.locator('.kpi').count(),4);await nav('Trends').click();
 await page.locator('.recharts-line-curve').first().waitFor();
 assert.equal(await page.locator('.kpi').count(),0);
 assert.equal(await page.locator('.category-link').count(),0);
 assert.equal(await page.getByLabel('Product filter').count(),0);
 await noOverflow();await page.screenshot({path:'qa/trends-v3-desktop.png',fullPage:true,animations:'disabled'});
 passed.push('Separate Dashboard, Trends, Priorities and Reports pages; no product picker');
 const overview=await page.request.get(base+'/api/dashboard/overview').then(r=>r.json());
 const first=overview.categories.find(c=>c.negative>20);
 const chartResponse=page.waitForResponse(r=>r.url().includes('/dashboard/overview?')&&r.url().includes(first.id));
 await page.getByLabel('Chart category').selectOption(first.id);const filtered=await (await chartResponse).json();
 assert.equal(filtered.trends.reduce((s,t)=>s+t.negative,0),first.negative);
 assert.deepEqual(filtered.summary,overview.summary);
 await page.getByRole('button',{name:'Share of feedback',exact:true}).click();
 await page.getByText('Share uses all analyzed feedback',{exact:false}).waitFor();
 passed.push('Category filtering changes chart only; normalized share view works');
 await nav('Priorities').click();await page.locator('.category-link').first().waitFor();assert.equal(await page.locator('.trend-chart').count(),0);assert.equal(await page.locator('.category-link').count(),8);const scores=await page.locator('.priority-score>strong').allTextContents();assert.deepEqual(scores.map(Number),scores.map(Number).sort((a,b)=>b-a));await page.screenshot({path:'qa/priorities-v3-desktop.png',fullPage:true,animations:'disabled'});await page.getByRole('button',{name:`View evidence for ${first.label}`,exact:true}).click();
 const dialog=page.getByRole('dialog');await dialog.locator('.review').first().waitFor();
 await page.waitForFunction(()=>document.querySelector('.evidence-list').getAttribute('aria-busy')==='false');
 assert.equal(await dialog.locator('.review').count(),20);
 await dialog.getByRole('button',{name:'Next',exact:true}).click();await page.getByText('Page 2 of',{exact:false}).waitFor();
 await page.waitForFunction(()=>document.querySelector('.evidence-list').getAttribute('aria-busy')==='false');
 await dialog.getByRole('button',{name:/All feedback/}).click();
 await dialog.getByLabel('Search evidence').fill('unfindable-qa-987');await page.getByRole('heading',{name:'No matching reviews'}).waitFor();
 await dialog.getByLabel('Search evidence').fill('');await dialog.locator('.review').first().waitFor();
 const downloadPromise=page.waitForEvent('download');await page.getByRole('link',{name:'Export this view'}).click();
 const download=await downloadPromise;await download.saveAs('qa/evidence-v3-export.csv');
 assert.ok(fs.readFileSync('qa/evidence-v3-export.csv','utf8').includes('sentiment_method'));
 await page.screenshot({path:'qa/evidence-v3-desktop.png',fullPage:true,animations:'disabled'});await page.keyboard.press('Escape');
 passed.push('Complete paginated evidence, sentiment toggle, search and CSV export');
 await nav('Generate report').click();await page.getByLabel('Report title',{exact:true}).fill('Support performance review');await page.screenshot({path:'qa/generate-report-v3.png',fullPage:true,animations:'disabled'});assert.equal(await page.locator('.priority-table').count(),0);const reportResponse=page.waitForResponse(r=>r.url().endsWith('/api/reports')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'Generate performance report'}).click();
 const rid=(await (await reportResponse).json()).id;
 await page.getByRole('heading',{name:'Customer feedback performance',exact:true}).waitFor();
 await page.screenshot({path:'qa/report-v3-desktop.png',fullPage:true,animations:'disabled'});
 const reportDownload=page.waitForEvent('download');await page.getByRole('link',{name:'Download report'}).click();
 await (await reportDownload).saveAs('qa/performance-v3-report.html');
 assert.ok(fs.readFileSync('qa/performance-v3-report.html','utf8').includes('Frozen at generation time'));
 await page.reload();await page.locator('.report-list-row').first().waitFor();await page.locator('.report-list-row').first().click();
 await page.getByRole('heading',{name:'Customer feedback performance',exact:true}).waitFor();
 await page.getByRole('button',{name:`View evidence for ${first.label}`,exact:true}).click();await dialog.locator('.review').first().waitFor();
 assert.equal(await dialog.getByText('Edit category display name',{exact:true}).count(),0);await page.keyboard.press('Escape');
 passed.push('Report generation, standalone download, archive reload and frozen evidence');
 await nav('Dashboard').click();await page.getByRole('button',{name:'Import feedback',exact:true}).click();
 await page.getByLabel('Choose feedback CSV').setInputFiles({name:'bad.csv',mimeType:'text/csv',buffer:Buffer.from('content,review_date\nBad date,not-date')});
 await dialog.getByRole('button',{name:'Import & analyze'}).click();await dialog.getByRole('alert').waitFor();
 assert.match(await dialog.getByRole('alert').innerText(),/Nothing imported/);await dialog.getByRole('button',{name:'Cancel',exact:true}).click();
 passed.push('Invalid CSV reports errors and preserves current data');
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.scrollTo(0,0));await page.waitForFunction(()=>document.querySelector('.sidebar').getBoundingClientRect().right<=0);await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);await noOverflow();await page.screenshot({path:'qa/dashboard-v3-mobile.png',fullPage:true,animations:'disabled'});
 await page.getByRole('button',{name:'Import feedback',exact:true}).click();await noOverflow();await page.screenshot({path:'qa/import-v3-mobile.png',fullPage:true,animations:'disabled'});await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Open navigation'}).click();await nav('Report history').click();await page.locator('.report-list-row').first().waitFor();await noOverflow();
 passed.push('390px layout, mobile navigation and modal keyboard dismissal');
 // Mutating end-to-end import operates only on the isolated QA database.
 await page.setViewportSize({width:1440,height:1000});await nav('Dashboard').click();await page.getByRole('button',{name:'Import feedback',exact:true}).click();
 await page.getByLabel('Choose feedback CSV').setInputFiles({name:'company.csv',mimeType:'text/csv',buffer:Buffer.from('content,review_date,service,segment\nThe invoice export fails every time we try to download our monthly billing statement.,2026-09-01,Billing,Enterprise')});
 await page.getByLabel('Import behavior').selectOption('replace');await dialog.getByRole('checkbox').check();
 const newRunResponse=page.waitForResponse(r=>r.url().includes('/pipeline/run?')&&r.request().method()==='POST');await dialog.getByRole('button',{name:'Import & analyze'}).click();const newRun=await (await newRunResponse).json();await dialog.waitFor({state:'hidden'});
 let status; const deadline=Date.now()+180000;
 do {status=await page.request.get(base+'/api/pipeline/status').then(r=>r.json());if(status.id===newRun.id&&['completed','failed'].includes(status.status))break;await page.waitForTimeout(300);} while(Date.now()<deadline);
 assert.equal(status.id,newRun.id);assert.equal(status.status,'completed',status.error);
 const after=await page.request.get(base+'/api/dashboard/overview').then(r=>r.json());assert.equal(after.summary.total,1);assert.equal(after.summary.analyzed,1);assert.equal(after.services[0].name,'Billing');
 const historical=await page.request.get(base+`/api/reports/${rid}`).then(r=>r.json());assert.equal(historical.summary.analyzed,overview.summary.analyzed);
 const historicalEvidence=await page.request.get(base+`/api/reports/${rid}/reviews?topic_id=${first.id}&sentiment=negative`).then(r=>r.json());assert.equal(historicalEvidence.total,first.negative);
 passed.push('CSV without app or rating imports and runs real semantic analysis; replacement preserves report evidence');
 await nav('Report history').click();await page.locator('.report-list-row').first().waitFor();await page.screenshot({path:'qa/report-history-v3.png',fullPage:true,animations:'disabled'});
 await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.getByRole('heading',{name:'Welcome back'}).waitFor();
 await page.getByRole('button',{name:'Create an account',exact:true}).click();await page.getByLabel('Username',{exact:true}).fill(username+'-other');await page.getByLabel('Password',{exact:true}).fill(password);await page.getByLabel('Confirm password',{exact:true}).fill(password);await page.getByRole('button',{name:'Create account',exact:true}).click();await page.locator('.kpi').first().waitFor();assert.equal(await page.locator('.kpi strong').first().innerText(),'0');await nav('Report history').click();await page.getByRole('heading',{name:'Your reporting history starts here'}).waitFor();assert.equal((await page.request.get(base+`/api/reports/${rid}`)).status(),404);
 await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.getByLabel('Username',{exact:true}).fill(username);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.locator('.kpi').first().waitFor();await nav('Report history').click();await page.locator('.report-list-row').first().waitFor();
 passed.push('Username/password registration and login; second account cannot see first account data, reports or direct report URLs; history survives sign-out');
 assert.deepEqual(errors,[]);fs.writeFileSync('qa/browser-results-v3.json',JSON.stringify({passed,errors},null,2));console.log(JSON.stringify({passed,errors},null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
